name: C/C++ CI

on:
  push:
    branches: [ "troika-fixes" ]
  pull_request:
    branches: [ "troika-fixes" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.1
    - name: CI Build
      run: chmod +x ci-build.sh && ./ci-build.sh

    - uses: actions/upload-artifact@v4.1
      with:
        name: Galaxy A10
        path: ./workspace/workspace/kernel
